import 'package:meta/meta.dart';

/// Base class for all aggregate identifiers defined in the constitution §I.
///
/// Invariants:
/// - The raw `value` must not be empty.
/// - Two identifiers are equal if and only if they have the same concrete type
///   and the same `value`. Identifiers of different concept types are never
///   considered equal even when they share an underlying ULID.
@immutable
abstract class Identifier {
  Identifier(this.value) {
    if (value.isEmpty) {
      throw ArgumentError.value(
        value,
        'value',
        '$runtimeType must not be empty',
      );
    }
  }

  final String value;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      (other is Identifier &&
          other.runtimeType == runtimeType &&
          other.value == value);

  @override
  int get hashCode => Object.hash(runtimeType, value);

  @override
  String toString() => '$runtimeType($value)';
}

/// Identifier for a learner (the authenticated end user of the mobile app).
class LearnerIdentifier extends Identifier {
  LearnerIdentifier(super.value);
}

/// Identifier for the learner's registered vocabulary expression aggregate.
class VocabularyExpressionIdentifier extends Identifier {
  VocabularyExpressionIdentifier(super.value);
}

/// Identifier for an explanation aggregate produced by the explanation worker.
class ExplanationIdentifier extends Identifier {
  ExplanationIdentifier(super.value);
}

/// Identifier for a single sense within an explanation.
class SenseIdentifier extends Identifier {
  SenseIdentifier(super.value);
}

/// Identifier for a visual image aggregate produced by the image worker.
class VisualImageIdentifier extends Identifier {
  VisualImageIdentifier(super.value);
}

/// Identifier used by spec 008's auth handoff to reference a verified actor.
class ActorReferenceIdentifier extends Identifier {
  ActorReferenceIdentifier(super.value);
}

/// Identifier for a backend-verified session (spec 008).
class SessionIdentifier extends Identifier {
  SessionIdentifier(super.value);
}

/// Identifier for an auth account resolved by the backend after token verify.
class AuthAccountIdentifier extends Identifier {
  AuthAccountIdentifier(super.value);
}

/// Actor-scoped idempotency key generated by the client before dispatching a
/// command (spec 011).
class IdempotencyKey extends Identifier {
  IdempotencyKey(super.value);
}

/// Identifier for a store-side product reference (spec 014 product catalog).
class StoreProductIdentifier extends Identifier {
  StoreProductIdentifier(super.value);
}
