targets:
  $default:
    builders:
      ferry_generator|graphql_builder:
        enabled: true
        options:
          schema: vocastock_mobile|lib/src/infrastructure/graphql/schema.graphql
          custom_scalars:
            DateTime:
              type: DateTime
              import: "dart:core"
            Url:
              type: Uri
              import: "dart:core"
      ferry_generator|serializer_builder:
        enabled: true
      riverpod_generator|riverpod_generator:
        enabled: true
